spring.application.name=demo

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/orchestration_db
spring.datasource.username=springuser
spring.datasource.password=0000

# This will show the exact SQL and errors for every request
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# Python service
python.service.base-url=http://localhost:8000



